### PR TITLE
feat: make a tweet when an issue is raised

### PR DESCRIPTION
**Pull request by MarioSimou**
As a start, I have implemented the most simple solution, which extracts the title, author and the issue url and combines them to generate the tweet. There will be a following pr that generates the tweet content based on the issue type, but let's see how this one goes. 

I tested it in a dummy repo of mine and created the below tweet:

tweet

### CODE REVIEW

**Comment by MarioSimou** [comment]
I am not sure if you prefer to have a separate workflow for twitter, but I am open to both solutions. Either keep it as one with the split it

**Comment by PatrickHeneise** [comment]
One workflow with separate jobs is fine, they can be re-run individually. But CDC doesn't have a Twitter account (yet). Do you think that'd be useful?

**Comment by MarioSimou** [comment]
Do you mean if the tweet action is useful? If we are going to use twitter as a social platform to advertise some of the events organised from CDC, then yes. Otherwise, there isn't a big priority on this. We can close it and re-open it if we change our mind.

**Comment by PatrickHeneise** [comment]
Let's discuss on Discord about the Twitter account and if we have the capacity to manage that

**Comment by PatrickHeneise** [comment]
I'll add the Twitter credentials. Thanks!

**Review by PatrickHeneise — APPROVED** [review]

**Pull request merged**
